/*
 * generated by Xtext 2.13.0
 */
package dk.sdu.mmmi.mdsd.project.validation

import dk.sdu.mmmi.mdsd.project.dSL.Shelf
import org.eclipse.xtext.EcoreUtil2
import dk.sdu.mmmi.mdsd.project.dSL.DSLPackage
import org.eclipse.xtext.validation.Check
import dk.sdu.mmmi.mdsd.project.dSL.TaskTerminated
import dk.sdu.mmmi.mdsd.project.dSL.Task
import java.util.HashSet
import dk.sdu.mmmi.mdsd.project.dSL.Action
import dk.sdu.mmmi.mdsd.project.dSL.TaskItem
import dk.sdu.mmmi.mdsd.project.dSL.Condition
import dk.sdu.mmmi.mdsd.project.dSL.DoTask

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DSLValidator extends AbstractDSLValidator {
	

	public static val INVALID_NAME = 'Another shelf with the same name already exists';
	public static val INVALID_TERMINATABLE = "Two terminatables handlers can't have the same name";
	public static val CIRCULAR_REF = "Circular reference";
	
	@Check(FAST)
	def checkNames(Shelf s) {
		val container = EcoreUtil2.getRootContainer(s);
		val cand = EcoreUtil2.getAllContentsOfType(container, Shelf);
		
		for (Shelf myS : cand) {
			
			if (s != myS) {
				if (s.name.equals(myS.name)) {
					error(INVALID_NAME,  DSLPackage.Literals.AREA_ITEM__NAME);
				}
			}

		}
	}
	
	@Check(FAST)
	def checkTerminatable(TaskTerminated t) {
		val container = EcoreUtil2.getRootContainer(t)
		val cand = EcoreUtil2.getAllContentsOfType(container, TaskTerminated)
		
		for (TaskTerminated myT : cand) {
			if (t != myT) {
				if (t.terminatable.name.equals(myT.terminatable.name)) {
					error(INVALID_TERMINATABLE, DSLPackage.Literals.TASK_TERMINATED__TERMINATABLE);
				}
			}
		}
	}
	
	@Check(FAST)
	def checkCirculerTasks(Task t) {
		val set = new HashSet<Task>();
		set.add(t)
		if (taskCheck(t,set)) {
			error(CIRCULAR_REF, DSLPackage.Literals.TASK__ITEMS);
		}	
	}
	
	def boolean taskCheck(Task t, HashSet<Task> set) {
		
		val itemsOfTask = t.items
		
		for (TaskItem ti : itemsOfTask) {
			switch ti {
				DoTask : 
				if (set.contains(ti.task)) {
					return true;
				} else {
					set.add(ti.task)
					return taskCheck(ti.task, set);
				}
			}
		}
		return false
	}
	











	
}
